Update CI (#150)
* Update ci.yml

* Remove comment

* test IP

Signed-off-by: Nguyen Le Vu Long <vulongvn98@gmail.com>

* test CI

Signed-off-by: Nguyen Le Vu Long <vulongvn98@gmail.com>

* test fetchers in batch of 50

Signed-off-by: Nguyen Le Vu Long <vulongvn98@gmail.com>

* change batch size to 30

Signed-off-by: Nguyen Le Vu Long <vulongvn98@gmail.com>

* down batch size to 10

Signed-off-by: Nguyen Le Vu Long <vulongvn98@gmail.com>

* test sequentially instead of concurrently

Signed-off-by: Nguyen Le Vu Long <vulongvn98@gmail.com>

* format

Signed-off-by: Nguyen Le Vu Long <vulongvn98@gmail.com>

* remove test line

Signed-off-by: Nguyen Le Vu Long <vulongvn98@gmail.com>

---------

Signed-off-by: Nguyen Le Vu Long <vulongvn98@gmail.com>
Co-authored-by: Nguyen Le Vu Long <vulongvn98@gmail.com>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -22,6 +22,30 @@ jobs:
         run: npm run check-format
       - name: Run build
         run: npm run build
+      - name: Setup WireGuard
+        run: |
+          set -o errexit -o pipefail -o nounset
+          sudo apt-get update
+          sudo apt-get install -y wireguard-tools
+
+          sudo cat << EOL > wg0-client.conf
+          [Interface]
+          PrivateKey = ${{ secrets.WG_CLIENT_PRIVATE_KEY }}
+          Address = 10.0.0.2/32
+          [Peer]
+          PublicKey = ${{ secrets.WG_SERVER_PUBLIC_KEY }}
+          Endpoint = ${{ secrets.WG_SERVER_IP }}:${{ secrets.WG_SERVER_PORT }}
+          AllowedIPs = 0.0.0.0/0
+          EOL
+
+          sudo wg-quick up ./wg0-client.conf
+          # Check if the tunnel is up
+          if sudo wg show wg0-client | grep -q "peer: ${{ secrets.WG_SERVER_PUBLIC_KEY }}"; then
+            echo "Connected!"
+          else
+            echo "Connection failed!"
+            exit 1
+          fi
       - name: Run test
         run: npm test
         env:
